Upgrade services to elasticsearch 7.17.0
This is a prerequisite for upgrading to 8.0.0, going straight from
7.11 isn't allowed:

    java.lang.IllegalStateException: cannot upgrade a node from
    version [7.11.2] directly to version [8.0.0], upgrade to version
    [7.17.0] first.